### ISSUE TITLE
shopUrl配置问题

### ISSUE THREAD

**Issue by zjutjsj1004** [crlang/weeshop#2]
esshop3.6已经安装成功，并且可以进入后台：http://127.0.0.1:8080/ecshop/admin/index.php

那么我对应的shopUrl应该配置多少？
感觉按照你readme中说的，我应该配置：127.0.0.1:8080  但是都无法得到，希望可以指导，谢谢

**Comment by crlang** [comment]
问题已在博客评论回复讨论
